domains:
- domain: www.bakey.us
  type: PRIMARY
  zone: bakey.us
name: bakey-us
region: nyc
services:
- http_port: 80
  image:
    registry_type: DOCR
    repository: website
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bakey-us
  routes:
  - path: /