name: bakey.us
static_sites:
- build_command: hugo --destination ./public
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: bak3y/bakey-us-hugo
  name: bakey.us
  envs:
  - key: HUGO_VERSION
    scope: BUILD_TIME
    value: 0.80.0/extended
